export const surpriseMePrompts = [
  'an armchair in the shape of an avocado',
  'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
  'teddy bears shopping for groceries in Japan, ukiyo-e',
  'an oil painting by Matisse of a humanoid robot playing chess',
  'panda mad scientist mixing sparkling chemicals, digital art',
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
  'an astronaut lounging in a tropical resort in space, vaporwave',
  'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
  'a stained glass window depicting a hamburger and french fries',
  'a pencil and watercolor drawing of a bright city in the future with flying cars',
  'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
  'a fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  'an oil pastel drawing of an annoyed cat in a spaceship',
  'a painting of a fox in the style of Starry Night',
  'a bowl of soup that looks like a monster, knitted out of wool',
  'A plush toy robot sitting against a yellow wall',
  'A synthwave style sunset above the reflecting water of the sea, digital art',
  'Two futuristic towers with a skybridge covered in lush foliage, digital art',
  'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
  'A comic book cover of a superhero wearing headphones',
  'A centered explosion of colorful powder on a black background',
  'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
  'A photo of a white fur monster standing in a purple room',
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  'A Samurai riding a Horse on Mars, lomography.',
  'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
  'A realistic photograph of a young woman with blue eyes and blonde hair',
  'A man standing in front of a stargate to another dimension',
  'Spongebob Squarepants in the Blair Witch Project',
  'A velociraptor working at a hotdog stand, lomography',
  'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
  'A BBQ that is alive, in the style of a Pixar animated movie',
  'A futuristic cyborg dance club, neon lights',
  'The long-lost Star Wars 1990 Japanese Anime',
  'A hamburger in the shape of a Rubik’s cube, professional food photography',
  'A Synthwave Hedgehog, Blade Runner Cyberpunk',
  'An astronaut encountering an alien life form on a distant planet, photography',
  'A Dinosaur exploring Cape Town, photography',
  'A Man falling in Love with his Computer, digital art',
  'A photograph of a cyborg exploring Tokyo at night, lomography',
  'Dracula walking down the street of New York City in the 1920s, black and white photography',
  'Synthwave aeroplane',
  'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
  'A Space Shuttle flying above Cape Town, digital art',
  'A giant octopus wrapping its tentacles around a skyscraper, digital art',
  'A steampunk mechanical dragon flying over a Victorian city, digital art',
  'A robot chef preparing sushi in a futuristic kitchen, digital art',
  'A neon-lit alleyway in a cyberpunk city, with a cat wearing VR goggles',
  'A fairy-tale castle floating on a cloud at sunset, digital art',
  'A 3D render of a crystal dragon perched on a mountain peak',
  'A magical forest with glowing mushrooms and bioluminescent plants, digital art',
  'A sci-fi city skyline at dawn, with flying cars and towering skyscrapers',
  'A pirate ship sailing through the clouds, digital art',
  'A fantasy landscape with a giant treehouse village, digital art',
  'A 3D render of a futuristic motorcycle racing through a neon-lit tunnel',
  'A surreal painting of a fish swimming in the sky with clouds as waves',
  'A robot playing a grand piano in an abandoned concert hall, digital art',
  'A photograph of a glass orb reflecting a vibrant sunset over the ocean',
  'A dragon made of clouds flying over a mountain range, digital art',
  'A retro 80s style poster of a robot DJ at a neon-lit nightclub',
  'A whimsical illustration of a cat dressed as an astronaut exploring space',
  'A futuristic city with towering skyscrapers and flying drones, digital art',
  'A fantasy battle between a knight and a dragon in a stormy landscape, digital art',
  'A robotic hand holding a delicate butterfly, digital art',
  'A photo of a steampunk airship flying above the clouds at sunset',
  'A 3D render of a floating island with waterfalls and lush greenery',
  'A digital painting of a phoenix rising from the ashes in a burst of flames',
  'A sci-fi scene of astronauts discovering an alien temple on a distant planet',
  'A robot gardener tending to a garden of futuristic, glowing plants',
  'A whimsical illustration of a giraffe riding a bicycle through a forest',
  'A cyberpunk cityscape with neon signs and flying cars at night, digital art',
  'A detailed painting of a medieval castle under a starry night sky',
  'A 3D render of a giant jellyfish floating through a futuristic city',
  'A fantasy scene of a wizard casting a spell in an enchanted forest',
  'A robot dog playing fetch with a holographic ball, digital art',
  'A digital painting of a dragon curled around a crystal ball, glowing with light',
  'A futuristic landscape with towering crystal structures and floating islands',
  'A 3D render of a spaceship landing on an alien planet with two moons',
  'A surreal painting of a whale swimming through a desert sandstorm',
  'A photograph of a rainbow-colored butterfly perched on a glowing flower',
  'A cyberpunk samurai standing on a rooftop with a neon-lit city below, digital art',
  'A futuristic city with flying trains and towering skyscrapers, digital art',
  'A whimsical scene of a robot watering a garden of giant flowers, digital art',
  'A fantasy landscape with a giant tree shaped like a dragon, digital art',
  'A digital painting of a phoenix flying through a stormy sky with lightning',
  'A sci-fi scene of a spaceship landing on a distant, alien world',
  'A 3D render of a crystal cave with glowing, bioluminescent plants',
  'A digital painting of a dragon breathing fire in a snowy mountain landscape',
  'A whimsical illustration of a cat riding a dragon through a fantasy world',
  'A futuristic city with neon signs and flying cars at sunset, digital art',
  'A 3D render of a robot playing chess against a human in a futuristic setting',
  'A surreal painting of a city floating in the clouds, digital art',
  'A photograph of a rainbow-colored galaxy reflected in a lake at night',
];