import React, { useState } from 'react';
import { Loader } from '../components';
import PostList from '../components/PostList';

const Home = ({ posts, searchText }) => {
  const [loading, setLoading] = useState(false);

  return (
    <>
      <section className="max-w-7xl mx-auto mt-6">
        <div>
          <h1 className="font-extrabold text-[#222328] text-[32px]">
            The Community Showcase
          </h1>
          <p className="mt-2 text-[#666e75] text-[14px] max-w-[500px]">
            Browse through a collection of imaginative and visually stunning images
            generated by DALL-E AI
          </p>
        </div>

        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <PostList posts={posts} searchText={searchText} />
        )}
      </section>
    </>
  );
};

export default Home;
